.gitignore, app/Loaders/SprintLoader.php, app/Writers/SprintWriter.php, database/migrations/2022_02_26_161525_create_sprint_table.php
This PR renames the table from `sprints` to `sprint`.
=> Rename sprints table

Dockerfile, docker-compose.yaml
This PR changes some docker settings
=> Update docker files

database/migrations/2022_03_03_234741_create_day_table.php
This migration creates the day table.
=> Create day table

README.md
This PR updates the readme for our new laravel setup.
You can see what it would look like here https://github.com/jtowe1/sprint-report-api/blob/fdef6988dbc7985e14140105ed749070a1f20631/README.md
=> Update readme for laravel/sail setup

app/Models/Day.php
This PR updates the Day model.
=> Update Day Model

app/Hydrators/DayHydrator.php, app/Models/Day.php, database/migrations/2022_03_16_234913_add_total_goal_points_remaining_to_day.php
This PR adds the Total Goal Points Remaining column to the model, migration, and hydrator.
=> Add total goal points remaining to day

app/Writers/DayWriter.php
This PR creates the DayWriter.
=> creates daywriter

app/Repositories/DayRepository.php
This PR creates the Day Repository.
=> creates DayRepository

composer.json, composer.lock, phpcs.xml
This PR installs PHP Codesniffer and a basic set of rules.
=> installs php codesniffer

app/Hydrators/DayHydrator.php, app/Models/Day.php, app/Services/SprintChartService.php, app/Writers/DayWriter.php
This PR parses the current sprint day from jira and saves it to the day table in the database.
=> Parse Day Data

composer.lock
This PR updates composer packages.
=> updates composer packages

Dockerfile, config/logging.php, docker-compose-prod.yml, docker-compose.yml, docker/default.conf, docker/fastcgi-php.conf, docker/php-fpm.conf, docker/supervisord.ini, docker/www.conf
This PR reconfigures our docker setup to allow for dev and production builds.  It also gets us off of `sail`.
=> Setup docker for production

docker-compose.yml
This PR adds a `context` to the docker compose file
=> Add context to docker-compose

app/Hydrators/SprintHydrator.php, app/Loaders/DayLoader.php, app/Models/DayCollection.php, app/Models/Sprint.php, app/Repositories/DayRepository.php, app/Repositories/SprintRepository.php, app/Services/SprintChartService.php
This PR adds DayCollection to the Sprint model and returns a sprint with all recorded days from the sprint endpoint.
=> Load sprint with days

.github/workflows/docker-image-build-push-deploy.yml, config/cors.php
This PR sets up CORS for local and production, as well as configuring production to allow session cookies from `*.jeremiahtowe.com`
=> Setup CORS

routes/api.php
This PR guards the rest of our routes
=> Guard all routes

config/cors.php
This PR adds the logout route to cors.
=> Add logout to cors

config/session.php
This PR sets SameSite to none and sets https to true.
=> Change cookie settings

config/sanctum.php
This PR adds the react production url to sanctum.
=> Add react app url

docker-compose-prod.yml
This PR passes the SESSION_DOMAIN var into the prod docker image.
=> Add domain to prod
